defmodule Teste do
  require Logger
  alias Superlogica.Storage.Storage
  alias Superlogica.Helpers.Helpers
  alias Superlogica.Messages.ParseFile
  # alias Superlogica.Elastic.Elastic
  alias Superlogica.Requests.Webhooks
  # alias Superlogica.Helpers.Helpers
  # alias Superlogica.Condominos.Condominos
  alias Superlogica.Apis.SendMessage
  alias Superlogica.Apis.SendPdf
  alias Superlogica.Apis.SendSms
  # alias Superlogica.Elastic.Elastic
  alias Superlogica.Env.Env
  alias Superlogica.Helpers.ChronoUnit
  # alias Superlogica.Condominos.Reservations
  # use Timex
  # use GenServer
  alias Superlogica.Messages.Messages
  alias Superlogica.Chat.Chat
  alias Superlogica.Condominos.Expenses
  alias Superlogica.Condominos.Condominos
  alias Superlogica.Scheduler.QueueScheduler
  alias Superlogica.Helpers.Headers
  alias Superlogica.Condominium.Condominium
  alias Superlogica.Random.RandomValues
  alias Superlogica.Condominos.Reservations
  alias Superlogica.Condominium.LegalResponsibles
  use Timex

  # Teste2.teste("abc", "14425801008")

  @keys_reduce_reservation [
    {"fl_status_res", "status"},
    {"id_area_are", "area_id"},
    {"dt_reserva_res", "date"},
    {"id_condominio_cond", "condominium_id"},
    {"id_reserva_res", "reservation_id"},
    {"id_unidade_uni", "apartament_id"},
    {"st_bloco_uni", "block"},
    {"st_unidade_uni", "apartament"},
    {"vl_admvalorreserva_res", "price"},
    {"area_name", "area_name"},
    {"before_term", "minimum_reservation_days"},
    {"available_days", "maximum_reservation_days"}
  ]
  def teste do
    # list =
    [
      %{
        "area_name" => "Salão de Festas - Noite",
        "dt_emailreservanaopaga_res" => "",
        "dt_reserva_res" => "06/10/2021 00:00:00",
        "dt_reservarealizada_res" => "05/24/2021 00:00:00",
        "fl_status_res" => "1",
        "id_area_are" => "11",
        "id_condominio_cond" => "2",
        "id_recebimento_recb" => "",
        "id_receita_rec" => "",
        "id_reserva_res" => "1",
        "id_unidade_uni" => "1",
        "nm_fila_res" => "1",
        "st_bloco_uni" => "1",
        "st_email_res" => "E-mail não definido",
        "st_emailconfirmacao_res" => "tokenfoda",
        "st_fantasia_cond" => "Ilha de Dressrosa",
        "st_motivocancelamento_res" => "",
        "st_nome_cond" => "Ilha de Dressrosa",
        "st_reservadopor_res" => "tokenfoda",
        "st_unidade_uni" => "1001",
        "vl_admvalorreserva_res" => "35.00"
      },
      %{
        "available_days" => "30",
        "dt_emailreservanaopaga_res" => "",
        "dt_reserva_res" => "06/10/2021 00:00:00",
        "dt_reservarealizada_res" => "05/24/2021 00:00:00",
        "fl_status_res" => "1",
        "id_area_are" => "11",
        "id_condominio_cond" => "2",
        "id_recebimento_recb" => "",
        "id_receita_rec" => "",
        "id_reserva_res" => "1",
        "id_unidade_uni" => "1",
        "nm_fila_res" => "1",
        "st_bloco_uni" => "1",
        "st_email_res" => "E-mail não definido",
        "st_emailconfirmacao_res" => "tokenfoda",
        "st_fantasia_cond" => "Ilha de Dressrosa",
        "st_motivocancelamento_res" => "",
        "st_nome_cond" => "Ilha de Dressrosa",
        "st_reservadopor_res" => "tokenfoda",
        "st_unidade_uni" => "1001",
        "vl_admvalorreserva_res" => "35.00"
      },
      %{
        "before_term" => "1",
        "dt_emailreservanaopaga_res" => "",
        "dt_reserva_res" => "06/10/2021 00:00:00",
        "dt_reservarealizada_res" => "05/24/2021 00:00:00",
        "fl_status_res" => "1",
        "id_area_are" => "11",
        "id_condominio_cond" => "2",
        "id_recebimento_recb" => "",
        "id_receita_rec" => "",
        "id_reserva_res" => "1",
        "id_unidade_uni" => "1",
        "nm_fila_res" => "1",
        "st_bloco_uni" => "1",
        "st_email_res" => "E-mail não definido",
        "st_emailconfirmacao_res" => "tokenfoda",
        "st_fantasia_cond" => "Ilha de Dressrosa",
        "st_motivocancelamento_res" => "",
        "st_nome_cond" => "Ilha de Dressrosa",
        "st_reservadopor_res" => "tokenfoda",
        "st_unidade_uni" => "1001",
        "vl_admvalorreserva_res" => "35.00"
      },
      %{
        "area_name" => "Salão de Festas - Noite",
        "dt_emailreservanaopaga_res" => "",
        "dt_reserva_res" => "08/10/2021 00:00:00",
        "dt_reservarealizada_res" => "05/24/2021 00:00:00",
        "fl_status_res" => "1",
        "id_area_are" => "11",
        "id_condominio_cond" => "2",
        "id_recebimento_recb" => "",
        "id_receita_rec" => "",
        "id_reserva_res" => "2",
        "id_unidade_uni" => "1",
        "nm_fila_res" => "1",
        "st_bloco_uni" => "1",
        "st_email_res" => "E-mail não definido",
        "st_emailconfirmacao_res" => "tokenfoda",
        "st_fantasia_cond" => "Ilha de Dressrosa",
        "st_motivocancelamento_res" => "",
        "st_nome_cond" => "Ilha de Dressrosa",
        "st_reservadopor_res" => "tokenfoda",
        "st_unidade_uni" => "1001",
        "vl_admvalorreserva_res" => "35.00"
      },
      %{
        "available_days" => "30",
        "dt_emailreservanaopaga_res" => "",
        "dt_reserva_res" => "08/10/2021 00:00:00",
        "dt_reservarealizada_res" => "05/24/2021 00:00:00",
        "fl_status_res" => "1",
        "id_area_are" => "11",
        "id_condominio_cond" => "2",
        "id_recebimento_recb" => "",
        "id_receita_rec" => "",
        "id_reserva_res" => "2",
        "id_unidade_uni" => "1",
        "nm_fila_res" => "1",
        "st_bloco_uni" => "1",
        "st_email_res" => "E-mail não definido",
        "st_emailconfirmacao_res" => "tokenfoda",
        "st_fantasia_cond" => "Ilha de Dressrosa",
        "st_motivocancelamento_res" => "",
        "st_nome_cond" => "Ilha de Dressrosa",
        "st_reservadopor_res" => "tokenfoda",
        "st_unidade_uni" => "1001",
        "vl_admvalorreserva_res" => "35.00"
      },
      %{
        "before_term" => "1",
        "dt_emailreservanaopaga_res" => "",
        "dt_reserva_res" => "08/10/2021 00:00:00",
        "dt_reservarealizada_res" => "05/24/2021 00:00:00",
        "fl_status_res" => "1",
        "id_area_are" => "11",
        "id_condominio_cond" => "2",
        "id_recebimento_recb" => "",
        "id_receita_rec" => "",
        "id_reserva_res" => "2",
        "id_unidade_uni" => "1",
        "nm_fila_res" => "1",
        "st_bloco_uni" => "1",
        "st_email_res" => "E-mail não definido",
        "st_emailconfirmacao_res" => "tokenfoda",
        "st_fantasia_cond" => "Ilha de Dressrosa",
        "st_motivocancelamento_res" => "",
        "st_nome_cond" => "Ilha de Dressrosa",
        "st_reservadopor_res" => "tokenfoda",
        "st_unidade_uni" => "1001",
        "vl_admvalorreserva_res" => "35.00"
      },
      %{
        "area_name" => "Churrasqueira - Manhã",
        "dt_emailreservanaopaga_res" => "",
        "dt_reserva_res" => "06/10/2021 00:00:00",
        "dt_reservarealizada_res" => "05/25/2021 00:00:00",
        "fl_status_res" => "1",
        "id_area_are" => "12",
        "id_condominio_cond" => "2",
        "id_recebimento_recb" => "",
        "id_receita_rec" => "",
        "id_reserva_res" => "3",
        "id_unidade_uni" => "1",
        "nm_fila_res" => "1",
        "st_bloco_uni" => "1",
        "st_email_res" => "E-mail não definido",
        "st_emailconfirmacao_res" => "tokenfoda",
        "st_fantasia_cond" => "Ilha de Dressrosa",
        "st_motivocancelamento_res" => "",
        "st_nome_cond" => "Ilha de Dressrosa",
        "st_reservadopor_res" => "tokenfoda",
        "st_unidade_uni" => "1001",
        "vl_admvalorreserva_res" => "35.00"
      },
      %{
        "available_days" => "30",
        "dt_emailreservanaopaga_res" => "",
        "dt_reserva_res" => "06/10/2021 00:00:00",
        "dt_reservarealizada_res" => "05/25/2021 00:00:00",
        "fl_status_res" => "1",
        "id_area_are" => "12",
        "id_condominio_cond" => "2",
        "id_recebimento_recb" => "",
        "id_receita_rec" => "",
        "id_reserva_res" => "3",
        "id_unidade_uni" => "1",
        "nm_fila_res" => "1",
        "st_bloco_uni" => "1",
        "st_email_res" => "E-mail não definido",
        "st_emailconfirmacao_res" => "tokenfoda",
        "st_fantasia_cond" => "Ilha de Dressrosa",
        "st_motivocancelamento_res" => "",
        "st_nome_cond" => "Ilha de Dressrosa",
        "st_reservadopor_res" => "tokenfoda",
        "st_unidade_uni" => "1001",
        "vl_admvalorreserva_res" => "35.00"
      },
      %{
        "before_term" => "1",
        "dt_emailreservanaopaga_res" => "",
        "dt_reserva_res" => "06/10/2021 00:00:00",
        "dt_reservarealizada_res" => "05/25/2021 00:00:00",
        "fl_status_res" => "1",
        "id_area_are" => "12",
        "id_condominio_cond" => "2",
        "id_recebimento_recb" => "",
        "id_receita_rec" => "",
        "id_reserva_res" => "3",
        "id_unidade_uni" => "1",
        "nm_fila_res" => "1",
        "st_bloco_uni" => "1",
        "st_email_res" => "E-mail não definido",
        "st_emailconfirmacao_res" => "tokenfoda",
        "st_fantasia_cond" => "Ilha de Dressrosa",
        "st_motivocancelamento_res" => "",
        "st_nome_cond" => "Ilha de Dressrosa",
        "st_reservadopor_res" => "tokenfoda",
        "st_unidade_uni" => "1001",
        "vl_admvalorreserva_res" => "35.00"
      },
      %{
        "area_name" => "Churrasqueira - Tarde",
        "dt_emailreservanaopaga_res" => "",
        "dt_reserva_res" => "06/14/2021 00:00:00",
        "dt_reservarealizada_res" => "05/25/2021 00:00:00",
        "fl_status_res" => "1",
        "id_area_are" => "13",
        "id_condominio_cond" => "2",
        "id_recebimento_recb" => "",
        "id_receita_rec" => "",
        "id_reserva_res" => "4",
        "id_unidade_uni" => "1",
        "nm_fila_res" => "1",
        "st_bloco_uni" => "1",
        "st_email_res" => "E-mail não definido",
        "st_emailconfirmacao_res" => "tokenfoda",
        "st_fantasia_cond" => "Ilha de Dressrosa",
        "st_motivocancelamento_res" => "",
        "st_nome_cond" => "Ilha de Dressrosa",
        "st_reservadopor_res" => "tokenfoda",
        "st_unidade_uni" => "1001",
        "vl_admvalorreserva_res" => "35.00"
      },
      %{
        "available_days" => "30",
        "dt_emailreservanaopaga_res" => "",
        "dt_reserva_res" => "06/14/2021 00:00:00",
        "dt_reservarealizada_res" => "05/25/2021 00:00:00",
        "fl_status_res" => "1",
        "id_area_are" => "13",
        "id_condominio_cond" => "2",
        "id_recebimento_recb" => "",
        "id_receita_rec" => "",
        "id_reserva_res" => "4",
        "id_unidade_uni" => "1",
        "nm_fila_res" => "1",
        "st_bloco_uni" => "1",
        "st_email_res" => "E-mail não definido",
        "st_emailconfirmacao_res" => "tokenfoda",
        "st_fantasia_cond" => "Ilha de Dressrosa",
        "st_motivocancelamento_res" => "",
        "st_nome_cond" => "Ilha de Dressrosa",
        "st_reservadopor_res" => "tokenfoda",
        "st_unidade_uni" => "1001",
        "vl_admvalorreserva_res" => "35.00"
      },
      %{
        "before_term" => "1",
        "dt_emailreservanaopaga_res" => "",
        "dt_reserva_res" => "06/14/2021 00:00:00",
        "dt_reservarealizada_res" => "05/25/2021 00:00:00",
        "fl_status_res" => "1",
        "id_area_are" => "13",
        "id_condominio_cond" => "2",
        "id_recebimento_recb" => "",
        "id_receita_rec" => "",
        "id_reserva_res" => "4",
        "id_unidade_uni" => "1",
        "nm_fila_res" => "1",
        "st_bloco_uni" => "1",
        "st_email_res" => "E-mail não definido",
        "st_emailconfirmacao_res" => "tokenfoda",
        "st_fantasia_cond" => "Ilha de Dressrosa",
        "st_motivocancelamento_res" => "",
        "st_nome_cond" => "Ilha de Dressrosa",
        "st_reservadopor_res" => "tokenfoda",
        "st_unidade_uni" => "1001",
        "vl_admvalorreserva_res" => "35.00"
      },
      %{
        "area_name" => "Churrasqueira - Noite",
        "dt_emailreservanaopaga_res" => "",
        "dt_reserva_res" => "06/14/2021 00:00:00",
        "dt_reservarealizada_res" => "05/25/2021 00:00:00",
        "fl_status_res" => "1",
        "id_area_are" => "14",
        "id_condominio_cond" => "2",
        "id_recebimento_recb" => "",
        "id_receita_rec" => "",
        "id_reserva_res" => "5",
        "id_unidade_uni" => "1",
        "nm_fila_res" => "1",
        "st_bloco_uni" => "1",
        "st_email_res" => "E-mail não definido",
        "st_emailconfirmacao_res" => "tokenfoda",
        "st_fantasia_cond" => "Ilha de Dressrosa",
        "st_motivocancelamento_res" => "",
        "st_nome_cond" => "Ilha de Dressrosa",
        "st_reservadopor_res" => "tokenfoda",
        "st_unidade_uni" => "1001",
        "vl_admvalorreserva_res" => "35.00"
      },
      %{
        "available_days" => "30",
        "dt_emailreservanaopaga_res" => "",
        "dt_reserva_res" => "06/14/2021 00:00:00",
        "dt_reservarealizada_res" => "05/25/2021 00:00:00",
        "fl_status_res" => "1",
        "id_area_are" => "14",
        "id_condominio_cond" => "2",
        "id_recebimento_recb" => "",
        "id_receita_rec" => "",
        "id_reserva_res" => "5",
        "id_unidade_uni" => "1",
        "nm_fila_res" => "1",
        "st_bloco_uni" => "1",
        "st_email_res" => "E-mail não definido",
        "st_emailconfirmacao_res" => "tokenfoda",
        "st_fantasia_cond" => "Ilha de Dressrosa",
        "st_motivocancelamento_res" => "",
        "st_nome_cond" => "Ilha de Dressrosa",
        "st_reservadopor_res" => "tokenfoda",
        "st_unidade_uni" => "1001",
        "vl_admvalorreserva_res" => "35.00"
      },
      %{
        "before_term" => "1",
        "dt_emailreservanaopaga_res" => "",
        "dt_reserva_res" => "06/14/2021 00:00:00",
        "dt_reservarealizada_res" => "05/25/2021 00:00:00",
        "fl_status_res" => "1",
        "id_area_are" => "14",
        "id_condominio_cond" => "2",
        "id_recebimento_recb" => "",
        "id_receita_rec" => "",
        "id_reserva_res" => "5",
        "id_unidade_uni" => "1",
        "nm_fila_res" => "1",
        "st_bloco_uni" => "1",
        "st_email_res" => "E-mail não definido",
        "st_emailconfirmacao_res" => "tokenfoda",
        "st_fantasia_cond" => "Ilha de Dressrosa",
        "st_motivocancelamento_res" => "",
        "st_nome_cond" => "Ilha de Dressrosa",
        "st_reservadopor_res" => "tokenfoda",
        "st_unidade_uni" => "1001",
        "vl_admvalorreserva_res" => "35.00"
      },
      %{
        "area_name" => "Piscina - Tarde",
        "dt_emailreservanaopaga_res" => "",
        "dt_reserva_res" => "06/14/2021 00:00:00",
        "dt_reservarealizada_res" => "05/25/2021 00:00:00",
        "fl_status_res" => "1",
        "id_area_are" => "16",
        "id_condominio_cond" => "2",
        "id_recebimento_recb" => "",
        "id_receita_rec" => "",
        "id_reserva_res" => "6",
        "id_unidade_uni" => "1",
        "nm_fila_res" => "1",
        "st_bloco_uni" => "1",
        "st_email_res" => "E-mail não definido",
        "st_emailconfirmacao_res" => "tokenfoda",
        "st_fantasia_cond" => "Ilha de Dressrosa",
        "st_motivocancelamento_res" => "",
        "st_nome_cond" => "Ilha de Dressrosa",
        "st_reservadopor_res" => "tokenfoda",
        "st_unidade_uni" => "1001",
        "vl_admvalorreserva_res" => ""
      },
      %{
        "available_days" => "30",
        "dt_emailreservanaopaga_res" => "",
        "dt_reserva_res" => "06/14/2021 00:00:00",
        "dt_reservarealizada_res" => "05/25/2021 00:00:00",
        "fl_status_res" => "1",
        "id_area_are" => "16",
        "id_condominio_cond" => "2",
        "id_recebimento_recb" => "",
        "id_receita_rec" => "",
        "id_reserva_res" => "6",
        "id_unidade_uni" => "1",
        "nm_fila_res" => "1",
        "st_bloco_uni" => "1",
        "st_email_res" => "E-mail não definido",
        "st_emailconfirmacao_res" => "tokenfoda",
        "st_fantasia_cond" => "Ilha de Dressrosa",
        "st_motivocancelamento_res" => "",
        "st_nome_cond" => "Ilha de Dressrosa",
        "st_reservadopor_res" => "tokenfoda",
        "st_unidade_uni" => "1001",
        "vl_admvalorreserva_res" => ""
      },
      %{
        "before_term" => "1",
        "dt_emailreservanaopaga_res" => "",
        "dt_reserva_res" => "06/14/2021 00:00:00",
        "dt_reservarealizada_res" => "05/25/2021 00:00:00",
        "fl_status_res" => "1",
        "id_area_are" => "16",
        "id_condominio_cond" => "2",
        "id_recebimento_recb" => "",
        "id_receita_rec" => "",
        "id_reserva_res" => "6",
        "id_unidade_uni" => "1",
        "nm_fila_res" => "1",
        "st_bloco_uni" => "1",
        "st_email_res" => "E-mail não definido",
        "st_emailconfirmacao_res" => "tokenfoda",
        "st_fantasia_cond" => "Ilha de Dressrosa",
        "st_motivocancelamento_res" => "",
        "st_nome_cond" => "Ilha de Dressrosa",
        "st_reservadopor_res" => "tokenfoda",
        "st_unidade_uni" => "1001",
        "vl_admvalorreserva_res" => ""
      }
    ]
    # |> Enum.map(fn e -> reduce_reservation_fields(e) end)

    Reservations.reservations_list(2)

  end

  # defp reduce_reservation_fields(map_value) do
  #   keys = Enum.map(@keys_reduce_reservation, fn {key, _value} -> key end)
  #   Enum.reduce(@keys_reduce_reservation, %{}, fn {key, new_key}, map ->
  #     if(key in keys, do: Map.put(map, new_key, Map.get(map_value, key)))
  #   end)
  # end
end
